"""empty message

Revision ID: 311f7c3b61be
Revises: dedddb3086a1
Create Date: 2025-04-14 11:45:53.148095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '311f7c3b61be'
down_revision = 'dedddb3086a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
