"""empty message

Revision ID: 8d11a974b1e9
Revises: 9ac71ec98a97
Create Date: 2025-04-20 00:35:10.296849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d11a974b1e9'
down_revision = '9ac71ec98a97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grievance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grievance', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
