"""empty message

Revision ID: 9120a3455aba
Revises: 8d11a974b1e9
Create Date: 2025-04-21 06:47:54.257465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9120a3455aba'
down_revision = '8d11a974b1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('committee', schema=None) as batch_op:
        batch_op.drop_column('committee_local')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('committee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('committee_local', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
