"""empty message

Revision ID: 9ac71ec98a97
Revises: 84b450ed0f6c
Create Date: 2025-04-18 09:30:39.837162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ac71ec98a97'
down_revision = '84b450ed0f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grievance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('desc', sa.Text(), nullable=True))
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grievance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', mysql.TEXT(), nullable=True))
        batch_op.drop_column('desc')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
