"""empty message

Revision ID: ef3d0a55f5bc
Revises: 880625cfc0ec
Create Date: 2025-04-29 00:05:17.560654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3d0a55f5bc'
down_revision = '880625cfc0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grievance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grievance', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
